name: 'WinGet Updater'
description: 'Publish updates of your application to Windows Package Manager automatically.'
branding:
  color: blue
  icon: upload-cloud
inputs:
  komac-version:
    description: 'Which Komac version to use.'
    required: false
    default: '1.11.0'
  override-:
    description: ''
runs:
  using: "composite"
  steps:
    - name: Run Komac
      uses: michidk/run-komac
      with:
        komac-version: ${{ inputs.komac-version }}
        args: --version
      